# Server configuration
server.port=8080

# Logging
logging.level.com.example.employeeMvc=INFO

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# Development mode
spring.devtools.restart.enabled=true